### ISSUE TITLE
How do I pull only EC2 metrics using cloudwatch-dump command ?

### ISSUE THREAD

**Issue by sudhir6199** [mogproject/cloudwatch-dump#8]
Rather than filtering EC2 metrics after pulling is there any way to pull only EC2 metrics (cpu,diskspace,memory) using your cloudwatch-dump (https://github.com/mogproject/cloudwatch-dump) ? Just to reduce the amount of data pulled and save money.

**Comment by mogproject** [comment]
Unfortunately, the current version does not support filtering while pulling data.
